<a href="https://colab.research.google.com/github/wangare-Nduma/myportfolio/blob/main/Association_rule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.impute import SimpleImputer

import matplotlib.pyplot as plt

Dataset

In [ ]:
data=pd.read_csv('/content/vote.csv')
data.head()

,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa,Class
0,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y,republican
1,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN,republican
2,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n,democrat
3,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y,democrat
4,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y,democrat

In [ ]:
import numpy as np
transactions =[]
for i in range(0,435):
  transactions.append([str(data.values[i,j]) for j in range(0,17)])

print(transactions)

[['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'nan', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'nan', 'republican'], ['nan', 'y', 'y', 'nan', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'democrat'], ['n', 'y', 'y', 'n', 'nan', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'y', 'n', 'n', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'nan', 'y', 'y', 'y', 'y', 'democrat'], ['n', 'y', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'nan', 'y', 'y', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'nan', 'y', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'nan', 'nan', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'nan', 'nan', 'y', 'y', 'n', 'n', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'nan', 'y', 'y', 'nan', 'nan', 'republican'], ['n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'nan', 'nan', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'y', 'y', 'y', 'nan', 'y', 'y', 'nan', 'n', 'n', 'y', 'nan', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'nan', 'nan', 'n', 'nan', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'nan', 'n', 'nan', 'republican'], ['y', 'n', 'y', 'n', 'n', 'y', 'n', 'y', 'nan', 'y', 'y', 'y', 'nan', 'n', 'n', 'y', 'democrat'], ['y', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'nan', 'y', 'y', 'n', 'n', 'republican'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'nan', 'y', 'y', 'n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'nan', 'nan', 'y', 'y', 'democrat'], ['y', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'nan', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'n', 'y', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'n', 'y', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'nan', 'y', 'n', 'y', 'republican'], ['y', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'n', 'y', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'nan', 'n', 'n', 'n', 'n', 'nan', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'n', 'nan', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'nan', 'n', 'y', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'nan', 'n', 'n', 'n', 'n', 'n', 'n', 'nan', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'n', 'y', 'democrat'], ['n', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'nan', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'nan', 'nan', 'democrat'], ['y', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'y', 'y', 'n', 'n', 'y', 'nan', 'y', 'n', 'n', 'y', 'y', 'n', 'y', 'n', 'nan', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'nan', 'republican'], ['y', 'y', 'y', 'n', 'n', 'nan', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'nan', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'nan', 'n', 'n', 'n', 'y', 'democrat'], ['y', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'nan', 'democrat'], ['y', 'y', 'y', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'n', 'y', 'republican'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['y', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'y', 'y', 'n', 'y', 'republican'], ['y', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'y', 'y', 'democrat'], ['n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'n', 'y', 'y', 'n', 'n', 'democrat'], ['n', 'y', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'nan', 'democrat'], ['n', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'n', 'y', 'y', 'n', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'y', 'n', 'nan', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'nan', 'y', 'y', 'y', 'n', 'y', 'n', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'y', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'y', 'n', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'nan', 'y', 'y', 'n', 'nan', 'republican'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'n', 'y', 'y', 'n', 'n', 'nan', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'y', 'y', 'n', 'nan', 'nan', 'n', 'y', 'nan', 'nan', 'nan', 'y', 'y', 'democrat'], ['n', 'n', 'nan', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'y', 'democrat'], ['y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'y', 'y', 'n', 'n', 'y', 'n', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'nan', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'n', 'n', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'n', 'y', 'n', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'n', 'y', 'n', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'nan', 'n', 'y', 'n', 'y', 'y', 'y', 'nan', 'democrat'], ['y', 'n', 'n', 'n', 'y', 'y', 'nan', 'n', 'nan', 'n', 'n', 'n', 'n', 'y', 'nan', 'n', 'democrat'], ['nan', 'nan', 'nan', 'nan', 'n', 'y', 'y', 'y', 'y', 'y', 'nan', 'n', 'y', 'y', 'n', 'nan', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'y', 'nan', 'nan', 'republican'], ['y', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['y', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'nan', 'y', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['n', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['n', 'nan', 'y', 'n', 'nan', 'nan', 'y', 'y', 'y', 'y', 'nan', 'nan', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'nan', 'nan', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'nan', 'y', 'republican'], ['n', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'n', 'y', 'n', 'y', 'republican'], ['y', 'nan', 'n', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'y', 'y', 'democrat'], ['n', 'nan', 'y', 'n', 'n', 'y', 'n', 'y', 'n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['nan', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'nan', 'n', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'democrat'], ['y', 'nan', 'y', 'n', 'nan', 'nan', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'nan', 'republican'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'nan', 'republican'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'republican'], ['n', 'nan', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'y', 'n', 'y', 'republican'], ['n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'y', 'nan', 'y', 'republican'], ['n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['nan', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'y', 'y', 'democrat'], ['n', 'nan', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'nan', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'nan', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'y', 'y', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'n', 'y', 'y', 'democrat'], ['y', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['y', 'y', 'nan', 'y', 'y', 'y', 'n', 'n', 'y', 'n', 'y', 'nan', 'y', 'y', 'n', 'n', 'democrat'], ['n', 'y', 'y', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'y', 'y', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'n', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'y', 'n', 'y', 'y', 'y', 'n', 'nan', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'republican'], ['y', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'y', 'y', 'n', 'n', 'y', 'n', 'y', 'y', 'n', 'y', 'n', 'nan', 'nan', 'nan', 'nan', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'republican'], ['n', 'y', 'y', 'n', 'nan', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'nan', 'n', 'nan', 'democrat'], ['n', 'y', 'n', 'n', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'democrat'], ['n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'democrat'], ['n', 'y', 'y', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'y', 'democrat'], ['n', 'y', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['y', 'y', 'n', 'n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'nan', 'democrat'], ['n', 'y', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'y', 'nan', 'democrat'], ['y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'y', 'n', 'y', 'y', 'y', 'republican'], ['y', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'y', 'y', 'republican'], ['n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'nan', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'y', 'n', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'nan', 'y', 'y', 'nan', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['n', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'nan', 'n', 'y', 'y', 'democrat'], ['n', 'n', 'n', 'n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'democrat'], ['y', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'n', 'y', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'republican'], ['n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'nan', 'n', 'n', 'y', 'y', 'democrat'], ['nan', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'nan', 'n', 'n', 'y', 'nan', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['nan', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'nan', 'nan', 'n', 'n', 'n', 'nan', 'nan', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'nan', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'y', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'nan', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['y', 'nan', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'nan', 'y', 'nan', 'nan', 'republican'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'nan', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'nan', 'republican'], ['n', 'y', 'n', 'y', 'y', 'y', 'n', 'nan', 'n', 'y', 'n', 'y', 'y', 'y', 'n', 'nan', 'republican'], ['n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'y', 'y', 'nan', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'nan', 'republican'], ['n', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'y', 'y', 'n', 'y', 'y', 'nan', 'democrat'], ['n', 'nan', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'republican'], ['n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'nan', 'n', 'y', 'nan', 'democrat'], ['y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'nan', 'n', 'y', 'n', 'n', 'n', 'y', 'nan', 'democrat'], ['n', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'democrat'], ['y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['y', 'n', 'y', 'n', 'n', 'n', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'democrat'], ['n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'n', 'n', 'n', 'y', 'y', 'y', 'n', 'y', 'republican'], ['n', 'n', 'y', 'n', 'n', 'y', 'y', 'y', 'y', 'y', 'n', 'y', 'n', 'n', 'n', 'y', 'democrat'], ['n', 'n', 'n', 'y', 'y', 'y', 'n', 'n', 'n', 'y', 'n', 'y', 'n',

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
te= TransactionEncoder()
te_arry = te.fit(transactions).transform(transactions)
df= pd.DataFrame(te_arry, columns=te.columns_)
df

     democrat     n    nan  republican     y
0       False  True   True        True  True
1       False  True   True        True  True
2        True  True   True       False  True
3        True  True   True       False  True
4        True  True   True       False  True
..        ...   ...    ...         ...   ...
430     False  True  False        True  True
431      True  True  False       False  True
432     False  True   True        True  True
433     False  True   True        True  True
434     False  True   True        True  True

[435 rows x 5 columns]

In [ ]:
from mlxtend.frequent_patterns import apriori
ruleset = apriori(df, min_support=0.0045, use_colnames=True)
ruleset["length"]= ruleset["itemsets"].apply(lambda x: len(x))
ruleset

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

     support                 itemsets  length
0   0.613793               (democrat)       1
1   0.995402                      (n)       1
2   0.466667                    (nan)       1
3   0.386207             (republican)       1
4   0.997701                      (y)       1
5   0.611494            (democrat, n)       2
6   0.328736          (nan, democrat)       2
7   0.613793            (democrat, y)       2
8   0.462069                 (nan, n)       2
9   0.383908          (n, republican)       2
10  0.995402                   (n, y)       2
11  0.137931        (nan, republican)       2
12  0.464368                 (nan, y)       2
13  0.383908          (republican, y)       2
14  0.326437       (nan, democrat, n)       3
15  0.611494         (democrat, y, n)       3
16  0.328736       (nan, democrat, y)       3
17  0.135632     (nan, n, republican)       3
18  0.462069              (nan, n, y)       3
19  0.383908       (n, republican, y)       3
20  0.135632     (nan, republican, y)       3
21  0.326437    (nan, democrat, y, n)       4
22  0.135632  (nan, n, republican, y)       4

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
ruleset[(ruleset["length"]==3)&(ruleset["support"]>0.05)]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

     support              itemsets  length
14  0.326437    (nan, democrat, n)       3
15  0.611494      (democrat, y, n)       3
16  0.328736    (nan, democrat, y)       3
17  0.135632  (nan, n, republican)       3
18  0.462069           (nan, n, y)       3
19  0.383908    (n, republican, y)       3
20  0.135632  (nan, republican, y)       3

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
ruleset[ruleset["itemsets"] == frozenset({"democrat", "y"})]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

    support       itemsets  length
7  0.613793  (democrat, y)       2

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from mlxtend.frequent_patterns import association_rules
rules = association_rules(ruleset, metric="lift", min_threshold=1)
rules= rules.sort_values(["confidence","lift"], ascending=[False,False])
display(rules)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
27,"(republican, y)",(n),0.383908,0.995402,0.383908,1.000000,1.004619,1.0,0.001765,inf,0.007463,0.385681,1.000000,0.692841
41,"(nan, republican, y)",(n),0.135632,0.995402,0.135632,1.000000,1.004619,1.0,0.000624,inf,0.005319,0.136259,1.000000,0.568129
4,(democrat),(y),0.613793,0.997701,0.613793,1.000000,1.002304,1.0,0.001411,inf,0.005952,0.615207,1.000000,0.807604
6,(n),(y),0.995402,0.997701,0.995402,1.000000,1.002304,1.0,0.002288,inf,0.500000,0.997696,1.000000,0.998848
13,"(democrat, n)",(y),0.611494,0.997701,0.611494,1.000000,1.002304,1.0,0.001406,inf,0.005917,0.612903,1.000000,0.806452
18,"(nan, democrat)",(y),0.328736,0.997701,0.328736,1.000000,1.002304,1.0,0.000756,inf,0.003425,0.329493,1.000000,0.664747
24,"(nan, n)",(y),0.462069,0.997701,0.462069,1.000000,1.002304,1.0,0.001062,inf,0.004274,0.463134,1.000000,0.731567
26,"(n, republican)",(y),0.383908,0.997701,0.383908,1.000000,1.002304,1.0,0.000883,inf,0.003731,0.384793,1.000000,0.692396
30,"(nan, democrat, n)",(y),0.326437,0.997701,0.326437,1.000000,1.002304,1.0,0.000750,inf,0.003413,0.327189,1.000000,0.663594
40,"(nan, n, republican)",(y),0.135632,0.997701,0.135632,1.000000,1.002304,1.0,0.000312,inf,0.002660,0.135945,1.000000,0.567972
7,(y),(n),0.997701,0.995402,0.995402,0.997696,1.002304,1.0,0.002288,1.995402,1.000000,0.997696,0.498848,0.998848
0,(democrat),(n),0.613793,0.995402,0.611494,0.996255,1.000856,1.0,0.000523,1.227586,0.002215,0.612903,0.185393,0.805287
12,"(democrat, y)",(n),0.613793,0.995402,0.611494,0.996255,1.000856,1.0,0.000523,1.227586,0.002215,0.612903,0.185393,0.805287
15,(democrat),"(y, n)",0.613793,0.995402,0.611494,0.996255,1.000856,1.0,0.000523,1.227586,0.002215,0.612903,0.185393,0.805287
19,"(nan, y)",(democrat),0.464368,0.613793,0.328736,0.707921,1.153354,1.0,0.043710,1.322268,0.248237,0.438650,0.243723,0.621751
8,"(nan, n)",(democrat),0.462069,0.613793,0.326437,0.706468,1.150987,1.0,0.042822,1.315722,0.243861,0.435583,0.239961,0.619151
31,"(nan, y, n)",(democrat),0.462069,0.613793,0.326437,0.706468,1.150987,1.0,0.042822,1.315722,0.243861,0.435583,0.239961,0.619151
34,"(nan, n)","(democrat, y)",0.462069,0.613793,0.326437,0.706468,1.150987,1.0,0.042822,1.315722,0.243861,0.435583,0.239961,0.619151
2,(nan),(democrat),0.466667,0.613793,0.328736,0.704433,1.147673,1.0,0.042299,1.306667,0.241259,0.437309,0.234694,0.620007
21,(nan),"(democrat, y)",0.466667,0.613793,0.328736,0.704433,1.147673,1.0,0.042299,1.306667,0.241259,0.437309,0.234694,0.620007
33,"(nan, y)","(democrat, n)",0.464368,0.611494,0.326437,0.702970,1.149594,1.0,0.042479,1.307969,0.242943,0.435583,0.235456,0.618402
10,(nan),"(democrat, n)",0.466667,0.611494,0.326437,0.699507,1.143931,1.0,0.041073,1.292896,0.235915,0.434251,0.226543,0.616671
37,(nan),"(democrat, y, n)",0.466667,0.611494,0.326437,0.699507,1.143931,1.0,0.041073,1.292896,0.235915,0.434251,0.226543,0.616671
5,(y),(democrat),0.997701,0.613793,0.613793,0.615207,1.002304,1.0,0.001411,1.003675,1.000000,0.615207,0.003662,0.807604
1,(n),(democrat),0.995402,0.613793,0.611494,0.614319,1.000856,1.0,0.000523,1.001363,0.186090,0.612903,0.001361,0.805287
14,"(y, n)",(democrat),0.995402,0.613793,0.611494,0.614319,1.000856,1.0,0.000523,1.001363,0.186090,0.612903,0.001361,0.805287
17,(n),"(democrat, y)",0.995402,0.613793,0.611494,0.614319,1.000856,1.0,0.000523,1.001363,0.186090,0.612903,0.001361,0.805287
16,(y),"(democrat, n)",0.997701,0.611494,0.611494,0.612903,1.002304,1.0,0.001406,1.003640,1.000000,0.612903,0.003627,0.806452
22,(democrat),"(nan, y)",0.613793,0.464368,0.328736,0.535581,1.153354,1.0,0.043710,1.153337,0.344281,0.438650,0.132951,0.621751
3,(democrat),(nan),0.613793,0.466667,0.328736,0.535581,1.147673,1.0,0.042299,1.148387,0.333167,0.437309,0.129213,0.620007
20,"(democrat, y)",(nan),0.613793,0.466667,0.328736,0.535581,1.147673,1.0,0.042299,1.148387,0.333167,0.437309,0.129213,0.620007
36,"(democrat, n)","(nan, y)",0.611494,0.464368,0.326437,0.533835,1.149594,1.0,0.042479,1.149017,0.334945,0.435583,0.129691,0.618402
9,"(democrat, n)",(nan),0.611494,0.466667,0.326437,0.533835,1.143931,1.0,0.041073,1.144086,0.323860,0.434251,0.125940,0.616671
32,"(democrat, y, n)",(nan),0.611494,0.466667,0.326437,0.533835,1.143931,1.0,0.041073,1.144086,0.323860,0.434251,0.125940,0.616671
11,(democrat),"(nan, n)",0.613793,0.462069,0.326437,0.531835,1.150987,1.0,0.042822,1.149021,0.339663,0.435583,0.129694,0.619151
35,"(democrat, y)","(nan, n)",0.613793,0.462069,0.326437,0.531835,1.150987,1.0,0.042822,1.149021,0.339663,0.435583,0.129694,0.619151
38,(democrat),"(nan, y, n)",0.613793,0.462069,0.326437,0.531835,1.150987,1.0,0.042822,1.149021,0.339663,0.435583,0.129694,0.619151
25,(y),"(nan, n)",0.997701,0.462069,0.462069,0.463134,1.002304,1.0,0.001062,1.001983,1.000000,0.463134,0.001979,0.731567
28,(n),"(republican, y)",0.995402,0.383908,0.383908,0.385681,1.004619,1.0,0.001765,1.002887,1.000000,0.385681,0.002878,0.692841
29,(y),"(n, republican)",0.997701,0.383908,0.383908,0.384793,1.002304,1.0,0.000883,1.001438,1.000000,0.384793,0.001436,0.692396
23,(y),"(nan, democrat)",0.997701,0.328736,0.328736,0.329493,1.002304,1.0,0.000756,1.001130,1.000000,0.329493,0.001128,0.664747
39,(y),"(nan, democrat, n)",0.997701,0.326437,0.326437,0.327189,1.002304,1.0,0.000750,1.001118,1.000000,0.327189,0.001117,0.663594
42,(n),"(nan, republican, y)",0.995402,0.135632,0.135632,0.136259,1.004619,1.0,0.000624,1.000725,1.000000,0.136259,0.000725,0.568129
43,(y),"(nan, n, republican)",0.997701,0.135632,0.135632,0.135945,1.002304,1.0,0.000312,1.000362,1.000000,0.135945,0.000362,0.567972

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)